language: node_js
node_js:
  - 12

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./dist/website
  on:
    branch: master

branches:
  only:
    - master
