language: node_js
node_js:
  - 12

script:
  - npm install
  - npm run build
  - rm -rf data .travis.yml .gitignore
  - mv build/css .
  - mv build/js .
  - mv build/index.html .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./dist/website
  on:
    branch: master

branches:
  only:
    - master
